### ISSUE TITLE
assert failure

### ISSUE THREAD

**Issue by leite** [kengonakajima/luvit-mysql#3]
Hi Kengo,

thanks for this great project ...
I just set an app with luvit-mysql and got stuck in error : 

```
"state:9 i:33 c:2 recvd:29 len:78 index:0 lcl:nil lcsl:nil"
"state:9 i:34 c:0 recvd:30 len:78 index:1 lcl:nil lcsl:nil"
"state:10 i:35 c:15 recvd:31 len:78 index:0 lcl:nil lcsl:nil"
/opt/foo/modules/luvit-mysql/parser.lua:275: nil
stack traceback:
   [C]: in function 'assert'
   /opt/foo/modules/luvit-mysql/parser.lua:275: in function 'receive'
   /opt/foo/modules/luvit-mysql/client.lua:125: in function 'callback'
   /usr/local/lib/luvit/core.lua:213: in function 'emit'
   /usr/local/lib/luvit/net.lua:156: in function 'callback'
```

then I commented the line and the error is gone, I guess it is some incompatibility with the new version of mysql or with Percona ...

details:

(MySQL Percona-Server-5.5.28-rel29.2)
mysql --version
mysql  Ver 14.14 Distrib 5.5.28, for Linux (x86_64) using readline 5.1

luvit --version
0.6.0-16-g0f2bc30

**Comment by kengonakajima** [comment]
Thanks! I added some comments on the line for future users.
